# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from footsiesgym.footsies.game.proto import footsies_service_pb2 as footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in footsiesgym/footsies/game/proto/footsies_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class FootsiesGameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartGame = channel.unary_unary(
                '/FootsiesGameService/StartGame',
                request_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
                response_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
                _registered_method=True)
        self.ResetGame = channel.unary_unary(
                '/FootsiesGameService/ResetGame',
                request_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
                response_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
                _registered_method=True)
        self.StepNFrames = channel.unary_unary(
                '/FootsiesGameService/StepNFrames',
                request_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.StepInput.SerializeToString,
                response_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.GameState.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/FootsiesGameService/GetState',
                request_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
                response_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.GameState.FromString,
                _registered_method=True)
        self.GetEncodedState = channel.unary_unary(
                '/FootsiesGameService/GetEncodedState',
                request_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
                response_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.EncodedGameState.FromString,
                _registered_method=True)
        self.IsReady = channel.unary_unary(
                '/FootsiesGameService/IsReady',
                request_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
                response_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BoolValue.FromString,
                _registered_method=True)


class FootsiesGameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepNFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEncodedState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FootsiesGameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
                    response_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
            ),
            'ResetGame': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetGame,
                    request_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
                    response_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
            ),
            'StepNFrames': grpc.unary_unary_rpc_method_handler(
                    servicer.StepNFrames,
                    request_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.StepInput.FromString,
                    response_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.GameState.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
                    response_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.GameState.SerializeToString,
            ),
            'GetEncodedState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEncodedState,
                    request_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
                    response_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.EncodedGameState.SerializeToString,
            ),
            'IsReady': grpc.unary_unary_rpc_method_handler(
                    servicer.IsReady,
                    request_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
                    response_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BoolValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FootsiesGameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FootsiesGameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FootsiesGameService/StartGame',
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FootsiesGameService/ResetGame',
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepNFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FootsiesGameService/StepNFrames',
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.StepInput.SerializeToString,
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FootsiesGameService/GetState',
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEncodedState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FootsiesGameService/GetEncodedState',
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.EncodedGameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FootsiesGameService/IsReady',
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VectorizedFootsiesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitEnvironments = channel.unary_unary(
                '/VectorizedFootsiesService/InitEnvironments',
                request_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.InitEnvironmentsRequest.SerializeToString,
                response_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
                _registered_method=True)
        self.BatchStep = channel.unary_unary(
                '/VectorizedFootsiesService/BatchStep',
                request_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchStepInput.SerializeToString,
                response_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchEncodedState.FromString,
                _registered_method=True)
        self.BatchReset = channel.unary_unary(
                '/VectorizedFootsiesService/BatchReset',
                request_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchResetInput.SerializeToString,
                response_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchEncodedState.FromString,
                _registered_method=True)
        self.BatchResetAll = channel.unary_unary(
                '/VectorizedFootsiesService/BatchResetAll',
                request_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
                response_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchEncodedState.FromString,
                _registered_method=True)
        self.IsVecReady = channel.unary_unary(
                '/VectorizedFootsiesService/IsVecReady',
                request_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
                response_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BoolValue.FromString,
                _registered_method=True)


class VectorizedFootsiesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitEnvironments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchReset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchResetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsVecReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorizedFootsiesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitEnvironments': grpc.unary_unary_rpc_method_handler(
                    servicer.InitEnvironments,
                    request_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.InitEnvironmentsRequest.FromString,
                    response_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
            ),
            'BatchStep': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchStep,
                    request_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchStepInput.FromString,
                    response_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchEncodedState.SerializeToString,
            ),
            'BatchReset': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchReset,
                    request_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchResetInput.FromString,
                    response_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchEncodedState.SerializeToString,
            ),
            'BatchResetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchResetAll,
                    request_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
                    response_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchEncodedState.SerializeToString,
            ),
            'IsVecReady': grpc.unary_unary_rpc_method_handler(
                    servicer.IsVecReady,
                    request_deserializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
                    response_serializer=footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BoolValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VectorizedFootsiesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VectorizedFootsiesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitEnvironments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorizedFootsiesService/InitEnvironments',
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.InitEnvironmentsRequest.SerializeToString,
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorizedFootsiesService/BatchStep',
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchStepInput.SerializeToString,
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchEncodedState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchReset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorizedFootsiesService/BatchReset',
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchResetInput.SerializeToString,
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchEncodedState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchResetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorizedFootsiesService/BatchResetAll',
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BatchEncodedState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsVecReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorizedFootsiesService/IsVecReady',
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.Empty.SerializeToString,
            footsiesgym_dot_footsies_dot_game_dot_proto_dot_footsies__service__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
